version: "2.3"

services:

  codejail:
    build: .
    container_name: apparmor_codejail
    command: tail -f /dev/null
    security_opt:
      - apparmor:/home/sandbox/codejail_sandbox-python3.8/bin/python
