name: Apparmor CI

on:
  pull_request:

jobs:
  run_apparmor:
    name: AppArmor GitHub CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y apparmor-utils python3-virtualenv

    - name: Add Sandbox User & Group
      run: |
        sudo addgroup sandbox
        sudo adduser --disabled-login sandbox --ingroup sandbox

    - name: Create Virtualenv
      run: virtualenv codejailvenv

    - name: Activate Virtualenv
      run: source codejailvenv/bin/activate

    - name: Load Sandbox Sudoers Settings
      run: sudo mv apparmor-profiles/01-sandbox /etc/sudoers.d/

    - name: Check users
      run: id && whoami && id -u -n

    - name: Change owner of sudoers.d
      run: sudo pkexec chown root:root /etc/sudoers.d -R

    - name: Enforce sandbox user permissions
      run: sudo visudo -f /etc/sudoers.d/01-sandbox

    - name: Load AppArmor Profile
      run: sudo mv apparmor-profiles/home.runner.work.codejail.codejail.codejailvenv.bin.python /etc/apparmor.d/

    - name: Enforce apparmor profile
      run: sudo aa-enforce /etc/apparmor.d/home.runner.work.codejail.codejail.codejailvenv.bin.python

    - name: Check apparmor profiles status
      run: sudo aa-status

    - name: Install Requirements in Virtualenv
      run: |
        source codejailvenv/bin/activate
        pip install -r requirements/testing.txt
        pip install -r requirements/sandbox.txt

    - name: Run Quality Tests
      run: |
        source codejailvenv/bin/activate
        make quality

    - name: Run Tests
      env:
        CODEJAIL_TEST_USER: 'sandbox'
        CODEJAIL_TEST_VENV: 'codejailvenv'
      run: |
        source codejailvenv/bin/activate
        make test
