name: Apparmor CI

on:
  pull_request:

jobs:
  run_apparmor:
    name: AppArmor GitHub CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        apt-get update && apt-get install -y apparmor-utils

    - name: Install Python dependencies
      run: |
        pip install -r requirements/tox.txt
        pip install -r requirements/sandbox.txt

    - name: Run quality tests
      run: |
        tox -e quality
