name: Apparmor CI

on:
  pull_request:

jobs:
  run_apparmor:
    name: AppArmor GitHub Selfhosted CI
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]
        toxenv: [py38]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: build Image from Dockerfile
        run: docker build --tag codejail_apparmor .

      - name: Parse custom apparmor profile
        run: sudo apparmor_parser -r -W apparmor-profiles/home.sandbox.codejail_sandbox-python3.8.bin.python

      - name: Check apparmor profiles
        run: sudo aa-status

      - name: Check Kernal Params
        run: sudo sysctl -a
        
      - name: New Kernal Params
        run: sysctl -w lsm=landlock,lockdown,yama,apparmor,bpf

      - name: Run container with custom apparmor profile
        run: |
          docker run --name=codejail -d --security-opt apparmor=home.sandbox.codejail_sandbox-python3.8.bin.python codejail_apparmor tail -f /dev/null

      - name: Check AA status in docker container
        run: sudo docker exec -t codejail bash -c "aa-status"

      - name: Run Tests
        env:
          CODEJAIL_TEST_USER: "sandbox"
          CODEJAIL_TEST_VENV: "/home/sandbox/codejail_sandbox-python3.8"
        run: |
          sudo docker exec -t codejail bash -c "mkdir -p reports && CODEJAIL_PROXY=0 pytest --junitxml=reports/pytest-no-proxy.xml --log-level=DEBUG codejail && CODEJAIL_PROXY=1 pytest --junitxml=reports/pytest-proxy.xml --log-level=DEBUG codejail"