name: Apparmor CI

on:
  pull_request:

jobs:
  run_apparmor:
    name: AppArmor GitHub CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y apparmor-utils python3-virtualenv

    - name: Create Virtualenv
      run: sudo virtualenv codejailvenv

    - name: Activate Virtualenv
      run: source codejailvenv/bin/activate

    - name: Check generated Files
      run: ls codejailvenv/

    - name: Install Python dependencies
      run: |
        pip install -r requirements/tox.txt
        pip install -r requirements/sandbox.txt

    - name: Add Sandbox User & Group
      run: |
        sudo addgroup sandbox
        sudo adduser --disabled-login sandbox --ingroup sandbox

    - name: Load Sandbox Sudoers Settings
      run: sudo mv apparmor-profiles/01-sandbox /etc/sudoers.d/

    - name: Enforce apparmor profile
      run: sudo aa-enforce /etc/apparmor.d/home.runner.work.codejail.codejail.codejailvenv.bin.python

    - name: Check apparmor profiles status
      run: sudo aa-status

    - name: Run Quality Tests
      run: |
        source codejailvenv/bin/activate
        make quality

    - name: Run Tests
      env:
        CODEJAIL_TEST_USER: 'sandbox'
        CODEJAIL_TEST_VENV: 'codejailvenv'
      run: |
        source codejailvenv/bin/activate
        make test
