name: Apparmor CI

on:
  pull_request:

jobs:
  run_apparmor:
    name: AppArmor GitHub CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.8 ]
        toxenv: [py38, quality]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create Sandbox Group
      run: sudo groupadd sandbox

    - name: Create Sandbox User
      run: sudo useradd -gsandbox sandbox

    - name: Install system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y apparmor-utils python3-virtualenv

    - name: Create Virtualenv
      run: virtualenv -p python3.8 codejailvenv

    - name: Activate Virtualenv
      run: source codejailvenv/bin/activate

    - name: Check generated Files
      run: ls codejailvenv/

    - name: Install Python dependencies
      run: |
        pip install -r requirements/tox.txt
        pip install -r requirements/sandbox.txt

    - name: Load apparmor profile
      run: sudo mv apparmor-profiles/sandbox.bin.python /etc/apparmor.d/

    - name: Enforce apparmor profile
      run: sudo aa-enforce /etc/apparmor.d/sandbox.bin.python

    - name: Check apparmor profiles status
      run: sudo aa-status

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
        CODEJAIL_TEST_USER: 'sandbox'
        CODEJAIL_TEST_VENV: 'codejailvenv'
      run: tox
