name: Apparmor CI

on:
  pull_request:

jobs:
  run_apparmor:
    name: AppArmor GitHub CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.8 ]
        toxenv: [py38, quality]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y apparmor-utils python3-virtualenv

    - name: Create Virtualenv
      run: python3 -m venv codejail-venv

    - name: Activate Virtualenv
      run: source codejail-venv/bin/activate

    - name: Install Python dependencies
      run: |
        pip install -r requirements/tox.txt
        pip install -r requirements/sandbox.txt

    - name: Load apparmor profile
      run: sudo mv apparmor-profiles/codejail-venv.bin.python /etc/apparmor.d/

    - name: Enforce apparmor profile
      run: sudo aa-enforce /etc/apparmor.d/codejail-venv.bin.python

    - name: Check apparmor profiles status
      run: sudo aa-status

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
